### ISSUE TITLE
全局安装报错

### ISSUE THREAD

**Issue by liubin1023** [ant-design/antd-tools#25]
![image](https://cloud.githubusercontent.com/assets/6219316/21304056/a4d930a0-c5fd-11e6-993c-3010f74edb43.png)
![image](https://cloud.githubusercontent.com/assets/6219316/21304069/b40ddea4-c5fd-11e6-969e-fed04f728e95.png)

**Comment by bccsafe** [comment]
我也遇到了这个问题
```
npm -v
3.10.10
node -v
v6.9.4
```

**Comment by liubin1023** [comment]
@bccsafe 时间太久了，这东西好像不用安装也不能安装

**Comment by xiajian** [comment]
我也全局安装失败了，感觉好郁闷： 

```
hxpp@LAPTOP-0AF5POTQ MINGW64 /d/works/node/ant-design-mobile (master)
$ npm i antd-tools -g
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\hxpp\AppData\Roaming\npm\antd-tools-run -> C:\Users\hxpp\AppData\Roaming\npm\node_modules\antd-tools\bin\antd-tools-run.js@6.22.0reactpt\node_modules\glob-streamginugin-transform-es2015-modules-commonjsed-functions
C:\Users\hxpp\AppData\Roaming\npm\antd-tools -> C:\Users\hxpp\AppData\Roaming\npm\node_modules\antd-tools\bin\antd-tools.js
[                ..] - postinstall:tslint: sill lifecycle tslint@3.15.1~postinstall: no script for postinstall, continuingl, continuingnuingnuingntinuingostinstall: no script for postinstall, continuinginuing
> antd-tools@0.18.1 postinstall C:\Users\hxpp\AppData\Roaming\npm\node_modules\antd-tools
> node lib/init.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\hxpp\AppData\Roaming\npm\package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at init (C:\Users\hxpp\AppData\Roaming\npm\node_modules\antd-tools\lib\init.js:82:15)
    at Object.<anonymous> (C:\Users\hxpp\AppData\Roaming\npm\node_modules\antd-tools\lib\init.js:92:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
C:\Users\hxpp\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\antd-tools\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "antd-tools" "-g"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! antd-tools@0.18.1 postinstall: `node lib/init.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd-tools@0.18.1 postinstall script 'node lib/init.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/init.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\works\node\ant-design-mobile\npm-debug.log
npm ERR! code 1
```

ps: 我是在 windows 10 系统

**Comment by bccsafe** [comment]
@xiajian 不需要全局安装，项目目录下`npm install`就可以了

**Comment by xiajian** [comment]
@bccsafe 嗯，一开始，我 `npm install` 失败了，以为是要全局安装的。后来多试了几次 `npm install`，就好了。
